# Define o usuário do sistema operacional que executará os processos de trabalho do Nginx
user  nginx;

# Define a quantidade de processos worker automaticamente com base no número de núcleos de CPU disponíveis
worker_processes  auto;

# Configura o caminho do arquivo de log de erros do Nginx com nível de severidade 'warn'
error_log  /var/log/nginx/error.log warn;

# Define o arquivo onde será armazenado o identificador do processo principal (PID) do Nginx
pid        /var/run/nginx.pid;

# Bloco de configuração de eventos de rede e conexões
events {
    # Define o número máximo de conexões simultâneas que cada processo worker pode gerenciar
    worker_connections  1024;
}

# Bloco principal de configurações do servidor HTTP
http {
    # Inclui o mapeamento padrão de tipos MIME para extensões de arquivo conhecidas
    include       /etc/nginx/mime.types;

    # Define o tipo de conteúdo padrão caso o arquivo não corresponda a nenhum MIME type conhecido
    default_type  application/octet-stream;

    # Define o formato customizado 'main' para registro detalhado das requisições nos logs de acesso
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    # Define o arquivo de log onde todas as requisições HTTP serão registradas utilizando o formato 'main'
    access_log  /var/log/nginx/access.log  main;

    # Habilita o uso da chamada de sistema sendfile para transferência direta e eficiente de arquivos do disco para o socket de rede
    sendfile        on;

    # Define o tempo limite de persistência (em segundos) para manter as conexões HTTP keep-alive abertas
    keepalive_timeout  65;

    # Rate limiting global
    # Configura a zona de controle de taxa de requisições na memória (10MB) limitando a 20 requisições por segundo por endereço IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;

    # Inclui dinamicamente todos os arquivos de configuração de servidores virtuais presentes na pasta conf.d
    include /etc/nginx/conf.d/*.conf;
}
